### ISSUE TITLE
Add support for last_updated_at in SQL query

### ISSUE THREAD

**Issue by sbellity** [hull-ships/hull-sql#1]
The ship should allow SQL queries to run incrementally based on the last date of the last run. 

A very simple example of code would look like 

```sql
SELECT id as external_id, email as email, updated_at as updated_at
FROM users
WHERE updated_at > last_updated_at
```
where the last_updated_at is a variable declared in the wrapped SQL query.

2 options here : either support a templating engine (like mustache or liquid) to inject it at runtime or use user defined variables for the DB engines that support them 

#### MySQL

http://dev.mysql.com/doc/refman/5.7/en/user-variables.html

#### Postgres PL/PgSQL 

https://www.postgresql.org/docs/current/static/sql-createfunction.html

**Comment by michaloo** [comment]
Replaced by `import_days` solution.
